### ISSUE TITLE
[Bug] spike_train_synchrony module not importable

### ISSUE THREAD

**Issue by essink** [INM-6/elephant#96] opened 2022-10-13 09:01 UTC
**Describe the bug**
I wanted to use the Synchrotool, but the spike_train_synchrony module was not importable.

**To Reproduce**
1. pip install latest elephant
2. `import elephant` 
3. `elephant.spike_train_sychrony` fails with:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'elephant' has no attribute 'spike_train_sychrony'

**Expected behavior**
Import should work.

**Environment**
 - OS (e.g., Linux): Linux
 - How you installed elephant (`conda`, `pip`, source): pip
 - Python version: 3.10.4
 - `neo` python package version: 0.11.0
 - `elephant` python package version: 0.11.1

If I am not mistaken, it is just not listed in the `elephant/__init__.py`.

**Comment by mdenker** [comment] 2022-10-13 14:15
Hi @essink 
Thanks for the issue. Sadly, I'm not able to confirm the issue as of now (with python 3.10, pip install). Also, with the latest github dev release, I cannot reproduce the issue. Are you sure, the correct elephant is being imported?

**Comment by essink** [comment] 2022-10-13 15:42
Hi @mdenker,

thanks for checking. Just reconfirmed my problem (with python 3.10, pip install), and indeed I reported it wrongly. I just edited the issue report.

Sorry!

**Comment by mdenker** [comment] 2022-10-13 15:49
Ah, yes, this makes more sense. I'll make a PR on the main elephant git repo to include the sync module.

**Comment by mdenker** [comment] 2022-10-13 16:00
Fixed by #518

**Closed as completed by mdenker** 2022-10-13 16:00 UTC
